services:
  books-mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./.docker-data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
      - ./.docker-data/mongodb:/data/db

  books-mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - books-mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@books-mongo:27017/

#  spring-native-app:
#    container_name: spring-app
#    build:
#      context: .
#    restart: always
#    depends_on:
#      - mongo
#    ports:
#      - 8080:8080
#    volumes:
#      - ./src/main/resources/application-docker.yaml:/app/application.yaml
